name: Cloud API CI/CD
on:
  push:
    branches:
      - main
  
jobs: 
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Upload JSON Data to DynamoDB
        run: |
            aws dynamodb put-item \
            --table-name Resumes \
            --item file://Resume.json \
            --region ${{ secrets.AWS_REGION }}